### ISSUE TITLE
The Quality of Pretrained Melgan is not good

### ISSUE THREAD

**Issue by chazo1994** [KevinMIN95/StyleSpeech#17]
@KevinMIN95  I use this pretrained model: https://huggingface.co/Guan-Ting/StyleSpeech-MelGAN-vocoder-16kHz. And I also use this repos https://github.com/descriptinc/melgan-neurips for inference, but the output audio sound very bad, output pitch may changed.
[1463_infer.zip](https://github.com/KevinMIN95/StyleSpeech/files/8122858/1463_infer.zip)

@KevinMIN95 Could you please tag the author of this model if it necessary.

**Comment by DanielLin94144** [comment]
@chazo1994 Hi, I'm the author of this pre-trained MelGAN vocoder. I think the reason that the pitch shifting is due to the sampling rate mismatch. The output of this vocoder should be in 16k Hz, but your file is saved as 22500 Hz. Please check whether the problem gets fixed when saving in 16k Hz. Thanks!

**Comment by chazo1994** [comment]
@DanielLin94144   I found that the problem come from function "librosa.core.load" which automatically resample audio to default sampling rate =22050
